[versions]

compileSdk = "36"
targetSdk = "36"
minSdk = "26"

javaVersion = "17"

kotlin = "2.2.20"

compose-multiplatform = "1.10.0"
compose-hotReload = "1.0.0"

# https://github.com/google/ksp
ksp = "2.2.20-2.0.3"

# https://developer.android.com/build/releases/gradle-plugin#compatibility
agp = "9.0.0"

nexus-publish-plugin = "2.0.0"

dokka = "2.0.0"
junit = "4.13.2"
runner = "1.0.2"
espressoCore = "3.0.2"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.3"
androidx = "1.17.0"
material3 = "1.4.0"
material3-multiplatform = "1.10.0-alpha05"

filekit = "0.12.0"
batik = "1.17"
fop = "2.11"
pdfbox = "2.0.30"

[libraries]

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "appcompat" }

compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose-multiplatform" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose-multiplatform" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose-multiplatform" }
compose-material3-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3-multiplatform"  }

androidx-core = { module = "androidx.core:core", version.ref = "androidx" }

compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose-multiplatform" }

vinceglb-filekit-dialogs-compose = { group = "io.github.vinceglb", name = "filekit-dialogs-compose", version.ref = "filekit" }
apache-batik-transcoder = { module = "org.apache.xmlgraphics:batik-transcoder", version.ref = "batik" }
apache-fop = { module = "org.apache.xmlgraphics:fop", version.ref = "fop" }
apache-pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "pdfbox" }


# Build logic dependencies
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose-multiplatform" }
nexusPublish-gradlePlugin = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish-plugin" }
dokka-gradlePlugin = { module = "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin", version.ref = "dokka" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
runner = { group = "com.android.support.test", name = "runner", version.ref = "runner" }
espresso-core = { group = "com.android.support.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-hotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "compose-hotReload" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin"}
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexus-publish-plugin"}
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }

